### ISSUE TITLE
In the docker environment, the supervisor creates a client and requests the docker network

### ISSUE THREAD

**Issue by Ableson** [31z4/storm-docker#37] opened 2022-08-17 00:36 UTC
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/STORM/issues).***

### Expected behavior

Tell us what should happen.

### Actual behavior

Tell us what happens instead.

### Steps to reproduce the behavior

Tell us how to reproduce the issue.

### System configuration

Please include as much relevant information as possible.

**Comment by Ableson** [comment] 2022-08-17 00:37
[ERROR] Exception to create supervisor client for node 52c1dd09-711a-4e41-8f66-068c59512154-172.18.0.3: java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)

**Comment by Ableson** [comment] 2022-08-17 00:39
[INFO] Setting new assignment for topology id storm-test333-1-1660644520: Assignment(master_code_dir:/data, node_host:{52c1dd09-711a-4e41-8f66-068c59512154-172.18.0.3=192.168.109.131}, 
executor_node_port:{
[4, 4]=NodeInfo(node:52c1dd09-711a-4e41-8f66-068c59512154-172.18.0.3, port:[6703]),
 [3, 3]=NodeInfo(node:52c1dd09-711a-4e41-8f66-068c59512154-172.18.0.3, port:[6703]), 
[1, 2]=NodeInfo(node:52c1dd09-711a-4e41-8f66-068c59512154-172.18.0.3, port:[6703])}

**Comment by 31z4** [comment] 2023-01-19 09:05
Closing this because there're no steps to reproduce the behavior and no info about system configuration. Feel free to reopen with as much relevant info as possible.

**Closed as not planned by 31z4** 2023-01-19 09:05 UTC
