### ISSUE TITLE
Error on supervisor. ps: unrecognized option: p

### ISSUE THREAD

**Issue by ldlozano** [31z4/storm-docker#14] opened 2018-03-09 11:59 UTC
I'm starting in cluster mode with docker composer, and I have 2 issues

1. It's not creating logs, but nimbus.log
2. Supervisor is throwing ps: unrecognized option: p error.

Any help?

**Comment by 31z4** [comment] 2018-03-18 05:58
Hello @ldlozano. Sorry for the delay.  In order to hep you figure out the issue I nee additional information, like:
* What image and tag are you using.?
* How exactly do you start the cluster?
* What's you `stack.yml`?
* What exactly do you mean by "not creating logs"? What's the expected behaviour and what really happens?

**Comment by ryanmickler** [comment] 2018-05-15 23:51
I'm getting the same thing. After a supervisor job throws an exception. i pulled these logs out of kibana so forgive the formatting. Sounds like there is a `ps -p` somewhere trying to kill a process

```
3022 [main] WARN  o.a.s.u.Utils - STORM-VERSION new 1.1.2 old 1.1.2
-- | --
4495 [main] INFO  o.a.s.StormSubmitter - Finished submitting topology: kafka_ingestor_test
kill: can't kill pid 4492: No such process
ps: unrecognized option: p
 BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.
-
Show list of processes
-
Usage: ps [-o COL1,COL2=HEADER]
 -
-o COL1,COL2=HEADER```

**Comment by 31z4** [comment] 2018-05-20 15:36
Hi @ryanmickler. Could you please describe exact steps to reproduce the issue? Following [the issue template](https://github.com/31z4/storm-docker/blob/master/.github/issue_template.md) is much appreciated 🙏

**Comment by 31z4** [comment] 2018-12-16 10:57
Closing this because there's not enough information to reproduce the issue.

**Closed as completed by 31z4** 2018-12-16 10:57 UTC
